"""add artist label constraints

Revision ID: 017807cfccd8
Revises: 7650048c1bdf
Create Date: 2025-06-27 03:49:17.267231+00:00

"""

# mypy: ignore-errors

from __future__ import annotations

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "017807cfccd8"
down_revision: Union[str, None] = "7650048c1bdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artists_name"), table_name="artists")
    op.create_index(op.f("ix_artists_name"), "artists", ["name"], unique=True)
    op.drop_index(op.f("ix_labels_name"), table_name="labels")
    op.create_index(op.f("ix_labels_name"), "labels", ["name"], unique=True)
    op.create_unique_constraint(
        "uq_releases_name_label_id", "releases", ["name", "label_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_releases_name_label_id", "releases", type_="unique")
    op.drop_index(op.f("ix_labels_name"), table_name="labels")
    op.create_index(op.f("ix_labels_name"), "labels", ["name"], unique=False)
    op.drop_index(op.f("ix_artists_name"), table_name="artists")
    op.create_index(op.f("ix_artists_name"), "artists", ["name"], unique=False)
    # ### end Alembic commands ###
