"""add releases

Revision ID: 10d0776b0450
Revises: ea71ca8d347b
Create Date: 2026-01-04 10:24:46.841352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d0776b0450'
down_revision: Union[str, Sequence[str], None] = 'ea71ca8d347b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('label_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_id', 'code', name='uq_release_label_code')
    )
    op.create_index(op.f('ix_releases_created_by'), 'releases', ['created_by'], unique=False)
    op.create_index(op.f('ix_releases_id'), 'releases', ['id'], unique=True)
    op.create_index(op.f('ix_releases_updated_by'), 'releases', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releases_updated_by'), table_name='releases')
    op.drop_index(op.f('ix_releases_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_created_by'), table_name='releases')
    op.drop_table('releases')
    # ### end Alembic commands ###
