"""add isrc to track model

Revision ID: 1c519cfa6de3
Revises: fb4a9d48e5f7
Create Date: 2025-06-27 16:20:55.860962+00:00

"""

# mypy: ignore-errors

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c519cfa6de3"
down_revision: Union[str, None] = "fb4a9d48e5f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tracks", sa.Column("isrc", sa.String(), nullable=True))
    op.drop_constraint(op.f("uq_track_name_release_id"), "tracks", type_="unique")
    op.create_unique_constraint(
        "uq_track_name_release_id_isrc", "tracks", ["name", "release_id", "isrc"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_track_name_release_id_isrc", "tracks", type_="unique")
    op.create_unique_constraint(
        op.f("uq_track_name_release_id"),
        "tracks",
        ["name", "release_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("tracks", "isrc")
    # ### end Alembic commands ###
