"""add artists

Revision ID: 36a0cd3c81e7
Revises: 39f05825edaa
Create Date: 2026-01-04 11:51:55.708112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a0cd3c81e7'
down_revision: Union[str, Sequence[str], None] = '39f05825edaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_created_by'), 'artists', ['created_by'], unique=False)
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=True)
    op.create_index(op.f('ix_artists_updated_by'), 'artists', ['updated_by'], unique=False)
    op.create_table('track_artists',
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'track_id', name='uq_track_artist_pair')
    )
    op.create_index(op.f('ix_track_artists_created_by'), 'track_artists', ['created_by'], unique=False)
    op.create_index(op.f('ix_track_artists_id'), 'track_artists', ['id'], unique=True)
    op.create_index(op.f('ix_track_artists_updated_by'), 'track_artists', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_artists_updated_by'), table_name='track_artists')
    op.drop_index(op.f('ix_track_artists_id'), table_name='track_artists')
    op.drop_index(op.f('ix_track_artists_created_by'), table_name='track_artists')
    op.drop_table('track_artists')
    op.drop_index(op.f('ix_artists_updated_by'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_created_by'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
