"""add tracks

Revision ID: 39f05825edaa
Revises: 10d0776b0450
Create Date: 2026-01-04 10:51:03.415414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f05825edaa'
down_revision: Union[str, Sequence[str], None] = '10d0776b0450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isrc', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('release_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isrc')
    )
    op.create_index(op.f('ix_tracks_created_by'), 'tracks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=True)
    op.create_index(op.f('ix_tracks_updated_by'), 'tracks', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_updated_by'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_created_by'), table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
