"""add raw_layer_playlists_tracks_table

Revision ID: 3a1b2c3d4e5f
Revises: 7f2327e28935
Create Date: 2025-08-03 14:05:11.134521+00:00

"""

# mypy: ignore-errors

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a1b2c3d4e5f"
down_revision: Union[str, None] = "7f2327e28935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_layer_playlists_tracks",
        sa.Column("raw_layer_playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["raw_layer_playlist_id"], ["raw_layer_playlists.id"]),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"]),
        sa.PrimaryKeyConstraint("raw_layer_playlist_id", "track_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_layer_playlists_tracks")
    # ### end Alembic commands ###
