"""add core entities

Revision ID: 5c2c21b74078
Revises: 59470dc8b635
Create Date: 2025-06-17 14:45:08.668613+00:00

"""

# mypy: ignore-errors

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5c2c21b74078"
down_revision: Union[str, None] = "59470dc8b635"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artists_id"), "artists", ["id"], unique=False)
    op.create_index(op.f("ix_artists_name"), "artists", ["name"], unique=False)
    op.create_table(
        "external_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM("BEATPORT", "SPOTIFY", "TIDAL", name="provider_enum"),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            postgresql.ENUM(
                "ARTIST", "LABEL", "RELEASE", "TRACK", name="entity_type_enum"
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "entity_type",
            "external_id",
            name="uq_external_data_provider_entity_external_id",
        ),
    )
    op.create_index(op.f("ix_external_data_id"), "external_data", ["id"], unique=False)
    op.create_index(
        "ix_external_data_provider_entity_id",
        "external_data",
        ["provider", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_labels_id"), "labels", ["id"], unique=False)
    op.create_index(op.f("ix_labels_name"), "labels", ["name"], unique=False)
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("label_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["labels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_releases_id"), "releases", ["id"], unique=False)
    op.create_index(op.f("ix_releases_name"), "releases", ["name"], unique=False)
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("bpm", sa.Float(), nullable=True),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracks_id"), "tracks", ["id"], unique=False)
    op.create_index(op.f("ix_tracks_name"), "tracks", ["name"], unique=False)
    op.create_table(
        "track_artists",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("track_id", "artist_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track_artists")
    op.drop_index(op.f("ix_tracks_name"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_id"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_releases_name"), table_name="releases")
    op.drop_index(op.f("ix_releases_id"), table_name="releases")
    op.drop_table("releases")
    op.drop_index(op.f("ix_labels_name"), table_name="labels")
    op.drop_index(op.f("ix_labels_id"), table_name="labels")
    op.drop_table("labels")
    op.drop_index("ix_external_data_provider_entity_id", table_name="external_data")
    op.drop_index(op.f("ix_external_data_id"), table_name="external_data")
    op.drop_table("external_data")
    op.drop_index(op.f("ix_artists_name"), table_name="artists")
    op.drop_index(op.f("ix_artists_id"), table_name="artists")
    op.drop_table("artists")
    # ### end Alembic commands ###
