"""add_status_to_raw_layer_block

Revision ID: 7f2327e28935
Revises: 784ad09c9215
Create Date: 2025-08-03 08:23:41.792648+00:00

"""

# mypy: ignore-errors

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7f2327e28935"
down_revision: Union[str, None] = "784ad09c9215"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    raw_layer_block_status_enum = postgresql.ENUM(
        "NEW", "PROCESSED", name="raw_layer_block_status_enum"
    )
    raw_layer_block_status_enum.create(op.get_bind())
    op.add_column(
        "raw_layer_blocks",
        sa.Column(
            "status", raw_layer_block_status_enum, server_default="NEW", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_layer_blocks", "status")
    postgresql.ENUM(name="raw_layer_block_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
