"""add track uniqueness constraint

Revision ID: e5a4b3c2d1f0
Revises: 017807cfccd8
Create Date: 2025-06-29 12:00:00.000000+00:00

"""

# mypy: ignore-errors

from __future__ import annotations

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e5a4b3c2d1f0"
down_revision: Union[str, None] = "017807cfccd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_track_name_release_id", "tracks", ["name", "release_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_track_name_release_id", "tracks", type_="unique")
    # ### end Alembic commands ###
