"""remove release_date

Revision ID: fb4a9d48e5f7
Revises: 1a2b3c4d5e6f
Create Date: 2025-06-27 16:14:55.343962+00:00

"""

# mypy: ignore-errors

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb4a9d48e5f7"
down_revision: Union[str, None] = "1a2b3c4d5e6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("releases", "release_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "releases",
        sa.Column("release_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
